### ISSUE TITLE
Error when run demos through Docker

### ISSUE THREAD

**Issue by jyk816108** [finsberg/fenics-beat#28]
**Hi,  when I run endocardial_stimulation.py through Docker,a problem has arisen that I can't solve and I'd like some advice.thanks
The returned content is as follows:**
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lark/lexer.py", line 665, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/usr/lib/python3/dist-packages/lark/lexer.py", line 598, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '(' in the current parser context, at line 665 col 21

gammawu = gammaw*abs(Zetaw)
                    ^
Expected one of:
        * VARIABLE
        * NEWLINE
        * PLUS
        * HASH
        * NEG
        * SLASH
        * "**"
        * STAR
        * RPAR
        * COMMA

Previous tokens: Token('VARIABLE', 'abs')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/demos/./endocardial_stimulation.py", line 330, in <module>
    main()
  File "/app/demos/./endocardial_stimulation.py", line 220, in main
    ode = gotranx.load_ode(here / "ORdmm_Land.ode")
  File "/usr/lib/python3/dist-packages/gotranx/load.py", line 36, in load_ode
    return ode_from_string(fname.read_text(), name=fname.stem)
  File "/usr/lib/python3/dist-packages/gotranx/load.py", line 17, in ode_from_string
    result = parser.parse(text)
  File "/usr/lib/python3/dist-packages/lark/lark.py", line 658, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/usr/lib/python3/dist-packages/lark/parser_frontends.py", line 104, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/usr/lib/python3/dist-packages/lark/parsers/lalr_parser.py", line 42, in parse
    return self.parser.parse(lexer, start)
  File "/usr/lib/python3/dist-packages/lark/parsers/lalr_parser.py", line 88, in parse
    return self.parse_from_state(parser_state)
  File "/usr/lib/python3/dist-packages/lark/parsers/lalr_parser.py", line 111, in parse_from_state
    raise e
  File "/usr/lib/python3/dist-packages/lark/parsers/lalr_parser.py", line 100, in parse_from_state
    for token in state.lexer.lex(state):
  File "/usr/lib/python3/dist-packages/lark/lexer.py", line 674, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: Unexpected token Token('__ANON_1', '(Zetaw)') at line 665, column 21.
Expected one of:
        * $END
        * VARIABLE
        * EXPRESSIONS
        * NEWLINE
        * COMPONENT
        * PLUS
        * PARAMETERS
        * SLASH
        * NEG
        * STATES
        * "**"
        * STAR
        * HASH
Previous tokens: [Token('VARIABLE', 'abs')]

**Comment by finsberg** [comment]
Hi! Apologize for this. It is due to a recent change in `gotranx` (see https://github.com/finsberg/gotranx/pull/51) where `Abs`  should now be used instead of `abs`, so it should work if you just change `abs` to `Abs` in the `.ode` file. I will make sure to update the version on the repo.
